sudo: required
services:
    - docker

before_install:
    - docker build -t piotrek/docker-multi -f ./client/Dockerfile.dev ./client
     
script:
    - docker run -e CI=true piotrek/docker-multi npm test

after_success:
    - docker build -t piotrekjanus/client ./client
    - docker build -t piotrekjanus/worker ./worker
    - docker build -t piotrekjanus/nginx  ./nginx
    - docker build -t piotrekjanus/server ./server
    # Log into docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push to dockerhub
    - docker push piotrekjanus/client
    - docker push piotrekjanus/server
    - docker push piotrekjanus/nginx
    - docker push piotrekjanus/worker