sudo: required
services:
    - docker

before_install:
    - docker build -t piotrek/docker-multi -f ./client/Dockerfile.dev ./client
     
script:
    - docker run -e CI=true piotrek/docker-multi npm test

after_success:
    - docker build -t piotrek/client -f ./client
    - docker build -t piotrek/worker -f ./worker
    - docker build -t piotrek/nginx -f ./nginx
    - docker build -t piotrek/server -f./server
    # Log into docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push to dockerhub
    - docker push piotrek/client
    - docker push piotrek/server
    - docker push piotrek/nginx
    - docker push piotrek/worker